export  const jokes = [
    "Why don’t oysters donate to charity? Because they’re shellfish!",
    "I told my wife she should embrace her mistakes… she hugged me.",
    "They say money talks, but mine just waves goodbye.",
    "My girlfriend told me to stop impersonating a flamingo. I had to put my foot down.",
    "I used to run a dating service for chickens… but I was struggling to make hens meet.",
    "What do you call an apology written in dots and dashes? Remorse code.",
    "I told my date I wasn’t into carbs. She left because I was too cheesy.",
    "They said I couldn't become a robot engineer, but I showed them the nuts and bolts.",
    "I asked my wife if she’d like to start a new diet with me, and she said 'bite me!'",
    "Why do bees stay in their hives during winter? Swarm.",
    "I tried to organize a professional hide-and-seek competition, but it was a complete disaster. Good players are hard to find.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I was going to tell you a joke about construction, but I’m still working on it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I told my wife I saw a deer on the way to work. She said, 'How do you know he was headed to work?'",
    "I told my therapist I’m afraid of commitment. She said, 'Do you want to talk about it?' I said, 'Maybe.'",
    "What do you call fake spaghetti? An impasta.",
    "Why couldn’t the bicycle stand up by itself? It was two tired.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "Why did the math book look sad? It had too many problems.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "What do you call an alligator in a vest? An investigator.",
    "Why was the tomato blushing? Because it saw the salad dressing.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "How do you organize a space party? You planet.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "Why didn’t the skeleton go to the dance? He had no body to go with.",
    "Why did the picture go to jail? It was framed.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the cookie go to the doctor? It was feeling crumbly.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they’d be bagels.",
    "What do you call two birds in love? Tweethearts.",
    "Why did the melon jump into the lake? It wanted to be a watermelon.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "Why don’t skeletons ever get into arguments? They don’t have the guts.",
    "Why don’t eggs tell jokes? They might crack up.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why don’t vampires like garlic? Because it stinks.",
    "Why did the banana go to the party? Because it was a-peeling.",
    "What do you call a boomerang that doesn’t come back? A stick.",
    "Why was the math book unhappy? It had too many problems.",
    "Why did the physics book break up with the chemistry book? There was no reaction.",
    "Why can’t a leopard hide? Because it’s always spotted.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "What do you call a fish without an eye? Fsh.",
    "Why did the scarecrow become a successful politician? He was outstanding in his field.",
    "What’s a pirate’s favorite letter? You’d think it’s 'R,' but his first love is the 'C.'",
    "Why did the chicken cross the playground? To get to the other slide.",
    "Why can’t you trust stairs? Because they’re always up to something.",
    "Why don’t calendars ever get tired? Because they’re always up to date.",
    "Why can’t you give Elsa a math problem? Because she’ll let it go.",
    "Why did the barber win the race? He knew all the short cuts.",
    "Why did the frog take the bus? His car was toad.",
    "What do you call a cow with no legs? Ground beef.",
    "Why don’t cannibals eat clowns? Because they taste funny.",
    "Why don’t skeletons go trick-or-treating? Because they have no body to go with.",
    "What do you call a magic dog? A Labracadabrador.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why did the skeleton go to the barbecue? To get a spare rib.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "Why don’t eggs tell jokes? They might crack up.",
    "Why did the computer go to the doctor? It caught a byte.",
    "Why did the skeleton go to the party? To bone up on fun.",
    "What do you call a fake noodle? An impasta.",
    "Why did the bike fall over? It was two tired.",
    "Why did the computer break up with the internet? No connection.",
    "Why did the man sit on the clock? He wanted to be on time.",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "Why can’t skeletons play music? They don’t have the organs.",
    "What’s a tree’s favorite drink? Root beer.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why don’t calendars go out? They’re always up to date.",
    "Why was the math book unhappy? It had too many problems.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "What do you call cheese that isn’t yours? Nacho cheese."
  ];
  